<script type="text/javascript" src="http://code.jquery.com/jquery-1.8.2.js"></script>
<script type="text/javascript" src="http://code.jquery.com/ui/1.9.1/jquery-ui.js"></script>
<script type="text/javascript" src="${pageContext.servletContext.contextPath}/resources/js/jquery.timepicker.js"></script>
<script type="text/javascript" src="${pageContext.servletContext.contextPath}/resources/js/jquery.ui.spinner.js"></script>
<script type="text/javascript" src="${pageContext.servletContext.contextPath}/resources/js/jquery.tablesorter.min.js"></script>
<script type="text/javascript" src="${pageContext.servletContext.contextPath}/resources/js/jquery.numeric.js"></script>
<script type="text/javascript" src="${pageContext.servletContext.contextPath}/resources/js/hoverIntent.js"></script>
<script type="text/javascript" src="${pageContext.servletContext.contextPath}/resources/js/superfish.js"></script>
<script type="text/javascript" src="${pageContext.servletContext.contextPath}/resources/js/common.js"></script>